---
title: "Project Proposal"
author: "MadagaskaR"
output: 
  html_document:
    highlight: tango
    theme: united
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: false
    toc_depth: 3
date: "`r format(Sys.time(), '%d %B %Y')`"
---

## Group Members

- Barış SİVAS
- Neriman GÜRSOY
- Ozan Barış BAYKAN
- Sena KALEMCİ
- Tuğba ÜNAL



## Overview of Dataset

The dataset covers up all the recorded earthquakes in Turkey between 1910 and 2017.This data is obtained from [Kaggle](https://www.kaggle.com/caganseval/earthquake). Unfortunately, When we analyzed the data, we realized a gap between 1980 and 2000. Since the earthquake that occurred in 1999 was an important one in Turkish history, we will add its data. In the dataset, we have 24007 observations with 17 features.

You can find variables as below:

- id: id of earthquake
- date: date of earthquake
- time: time of earthquake
- lat: latitude of earthquake
- long: longitude of earthquake
- country: country of earthquake
- city: city of earthquake
- area: area of earthquake
- direction: direction of earthquake
- dist: distance of direction in km
- depth: depth of earthquake
- xm: xm of earthquake
- md: md of earthquake
- richter: Intensity of earthquake (Richter)
- mw: mw of earthquake
- ms: ms of earthquake
- mb: mb of earthquake


You can find the glimpse of the data below.
```{r message=FALSE, warning=FALSE, paged.print=TRUE}

library(readxl)
library(tidyverse)

raw_df <- read.csv("earthquake.csv")

glimpse(raw_df)

```

## Plan

Our tentative plan is as below:

-	Cleaning, tidying and manipulating the data
-	Using data visualizations to understand the data better
-	Forecasting the earthquakes and creating a model
-	To come up with a conclusion

